Update to Gymnasium 0.29.1
DoubleGremlin181/RubiksCubeGym pull request #4
Opened 2024-01-05 16:36 UTC by uranium11010

Also made sure to follow Gymnasium API, e.g. using `self.np_random` for random scramble and using `options` as input to self.reset()

2024-01-05 21:15 UTC, DoubleGremlin181 commented
Hi, Thanks for PR!
The changes seem great and I'll merge it once you bump the version as recommended.

2024-01-05 21:15 UTC, DoubleGremlin181 requested changes

2024-01-05 21:15 UTC, DoubleGremlin181 commented on setup.py
Recommend to bump version to 0.5.0

2024-01-08 19:59 UTC, uranium11010 commented on setup.py
Done!

2024-01-08 20:23 UTC, DoubleGremlin181 approved these changes

2024-01-08 20:23 UTC, merged